name: first workflow

on:
  push: 
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo " welcome to our first workflow "

      - name: checkout Repooooo
        uses: actions/checkout@6.0.2 

      - name: List Repoooo files
        run: ls -la
