name: manual workflow with button

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose env"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
        

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        run: echo "Deploying the Application to ${{ inputs.environment }} "

        
