name: testing node versions on 3 os

on: 
  workflow_dispatch:
  
jobs:
  job-1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x, 15.x, 16.x]
        
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ matrix.node-version }}
